import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Terms() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Mystic Sisterhood | Terms </title>
        <meta
          name="description"
          content="Mystic Sisterhood is a community full of good energy where creatives can support each other. We welcome all enlightened beings. Whether you are drawn to magical things, or just like the art, there is something here for everyone!"
        />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Caveat&family=Satisfy&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Link href="/">
        <img
          className={styles.logo}
          src="/images/mystic sisterhood logo color.png"
          style={{ cursor: "pointer" }}
        />
      </Link>
      <div className={styles.terms}>
        <h1>Terms and Conditions</h1>
        <p>
          Mystic Sisterhood is an Ethereum blockchain-based generative project
          consisting of 7,777 unique digital artworks (NFTs) displaying
          randomized traits hosted on an InterPlanetary File System (“IPFS”).
        </p>
        <p>
          The Mystic Sisterhood website is only an interface allowing
          participants to purchase digital collectibles. Users are entirely
          responsible for the safety and management of their own private
          Ethereum wallets and validating all transactions and contracts
          generated by this website before approval. Furthermore, as the Mystic
          Sisterhood smart contract runs on the Ethereum network, there is no
          ability to undo, reverse, or restore any transactions.
        </p>
        <p>
          These terms of service (“TOS”) are intended to provide clear,
          transparent guidelines for responsible ownership and use of Mystic
          Sisterhood.
        </p>
        <h2>Ownership</h2>
        <p>
          Mystic Sisterhood is fully owned by the Creative Team. Other than the
          Art, nothing herein gives you any rights to any other trademarks or
          intellectual property rights belonging to the Mystic Sisterhood
          Creative Team. All rights that are not specifically granted to the
          users, holders and owners of Mystic Sisterhood NFTs (“Holders”) are
          reserved by the Creative Team, including but not limited to the
          intellectual property and merchandising rights surrounding the Mystic
          Sisterhood name, which includes logos, trademarks, creative branding,
          the smart contract code, art and generative traits, design collateral,
          game development, and any representation of project funds or the
          community wallet. The above list is not exhaustive and will also
          encompass any other de facto rights of creative ownership.
        </p>
        <p>
          Subject to your continued compliance with these Terms, Mystic
          Sisterhood Creative Team grants you a worldwide, royalty-free license
          to use, copy, and display the purchased Art, along with any extensions
          that you choose to create or use, solely for the following purposes:
          (i) for your own personal, non-commercial use; (ii) as part of a
          marketplace that permits the purchase and sale of your Mystic
          Sisterhood NFT, provided that the marketplace cryptographically
          verifies each Mystic Sisterhood NFT owner’s rights to display the Art
          for their Mystic Sisterhood NFT to ensure that only the actual owner
          can display the Art; or (iii) as part of a third party website or
          application that permits the inclusion, involvement, or participation
          of your Mystic Sisterhood NFT provided that the website/application
          cryptographically verifies each Mystic Sisterhood owner’s rights to
          display the Art for their Mystic Sisterhood NFT ensure that only the
          actual owner can display the Art, and provided that the Art is no
          longer visible once the owner of the Mystic Sisterhood NFT leaves the
          website/application.
        </p>
        <p>
          The Holder agrees not to use, utilize, portray, advertise, distribute
          or otherwise market any Mystic Sisterhood NFT in any project or
          derivative work that involves hate speech, racism, pornography, or any
          other illegal or unlawful content. Upon sale or transfer of the NFT,
          any ownership or commercial rights are immediately transferred to the
          new Holder. No refunds shall be issued to any Holder upon a full and
          complete lawful purchase of any Mystic Sisterhood NFT. In the event
          that any Holder purchases a Mystic Sisterhood NFT through the
          secondary market, Holder shall be held accountable and will be bound
          by the Terms of Service which govern said secondary market platform.
        </p>
        <p>
          Subject to your continued compliance with these Terms, the Mystic
          Sisterhood Creative Team grants you an unlimited, worldwide license to
          use, copy, and display the purchased Art for the purpose of creating
          derivative works based upon the Art (“Commercial Use”). Examples of
          such Commercial Use would e.g. be the use of the Art to produce and
          sell merchandise products (T-Shirts etc.) displaying copies of the
          Art.
        </p>
        <h2>ART AND CREATIVE DESIGN</h2>
        <p>
          All art and creative design are exclusively owned by the Mystic
          Sisterhood Creative Team, with the exception of Mystic Sisterhood
          artwork corresponding to individual NFTs which are owned by the
          Holder. Mystic Sisterhood may bear elements of transformative fanart
          or caricatures which are rendered in good faith to add humor and
          satire to the project. Any Holder of a Mystic Sisterhood NFT bearing
          these elements has an individual responsibility to determine the
          appropriateness of subsequent usage.
        </p>
        <h2>TERMINATION</h2>
        <p>
          License applies only to the extent that the Holder continues to own
          the applicable purchased Mystic Sisterhood NFT. If at any time the
          Holder sells, trades, donates, gives away, transfers, or otherwise
          disposes of the purchased NFT (and related art) for any reason, the
          License shall immediately expire without the requirement of notice and
          be transferred along with the purchased NFT to its new owner.
        </p>
        <p>
          The Holder acknowledges that, by disposing of the art for its
          purchased NFT, it no longer qualifies as the owner of the art and thus
          no longer benefits from the rights granted by this License. Any use of
          the Mystic Sisterhood NFT including art after its disposal shall be
          considered as an infringing act.
        </p>
        <h2>CLASS ACTION WAIVER, JURISDICTION AND CHOICE OF LAW</h2>
        <p>
          You agree to waive any class action status, and any legal dispute
          around the Mystic Sisterhood project which you may choose to bring can
          only be done on an individual basis.
        </p>
        <h2>
          LIMITATIONS OF LIABILITY FOR GAS, FAILED TRANSACTIONS, SMART CONTRACT
          BUGS
        </h2>
        <p>
          Participants in minting Mystic Sisterhood NFTs agree to hold the
          project Creative Team harmless for any losses incurred as a
          consequence of minting an NFT. These potential losses include any gas
          fees for failed transactions, any excessive gas fees charged due to
          website or smart contract bugs, and any loss of any NFT due to website
          or smart contract bugs.
        </p>
        <h2>FEES AND PAYMENT</h2>
        <p>
          If you elect to purchase a Mystic Sisterhood NFT through the Site, any
          financial transactions that you engage in will be conducted solely
          through the Ethereum network. We will have no insight into or control
          over these payments or transactions, nor do we have the ability to
          reverse any transactions. We will have no liability to you or to any
          third party for any claims or damages that may arise as a result of
          any transactions that you engage or any other transactions that you
          conduct via the Ethereum network.
        </p>
        <p>
          Ethereum requires the payment of a transaction fee (a “Gas Fee”) for
          every transaction that occurs on the Ethereum network. The Gas Fee
          funds the network of computers that run the decentralized Ethereum
          network. This means that you will need to pay a Gas Fee for each
          transaction.
        </p>
        <h2>NO GUARANTEES OF VALUE</h2>
        <p>
          Mystic Sisterhood NFTs were created purely as collectibles, not as
          investment vehicles or substitutes for cryptocurrency. We make
          absolutely no promise or guarantee that these NFTs will subsequently
          retain monetary value in fiat, cash or cryptocurrency.
        </p>
        <h2>RISK ASSUMPTION</h2>
        <p>You accept and acknowledge each of the following</p>
        <ol type="A">
          <li>
            To the extent that you sell your Mystic Sisterhood NFT, please be
            aware that the prices of NFTs are extremely volatile and
            fluctuations in the prices of other NFTs and impact the price of
            your Mystic Sisterhood NFT both positively and negatively. Given the
            volatility, NFTs such as Mystic Sisterhood should not be considered
            an investment. You assume all risks in that connection.
          </li>
          <li>
            Ownership of a Mystic Sisterhood NFT confers ownership of digital
            artwork only. Accordingly, no information on this Site (or any other
            documents mentioned therein) is or may be considered to be advice or
            an invitation to enter into an agreement for any investment purpose.
            Further, nothing on this Site qualifies or is intended to be an
            offering of securities in any jurisdiction nor does it constitute an
            offer or an invitation to purchase shares, securities or other
            financial products. Due to the artistic nature of the project,
            Mystic Sisterhood has not been registered with or approved by any
            regulator in any jurisdiction. It remains your sole responsibility
            to assure that the purchase of the Mystic Sisterhood NFT and the
            associated art is in compliance with laws and regulations in your
            jurisdiction.
          </li>
          <li>
            You assume all risks associated with using an Internet-based
            currency, including, but not limited to, the risk of hardware,
            software and Internet connections, the risk of malicious software
            introduction, and the risk that third parties may obtain
            unauthorized access to information stored within your wallet.
          </li>
          <li>
            NFTs, cryptocurrencies and blockchain technology are relatively new
            and the regulatory landscape is unsettled. New regulations could
            negatively impact such technologies impacting the value for your
            Mystic Sisterhood NFT. You understand and accept all risk in that
            regard.
          </li>
          <li>
            You assume all responsibility for any adverse effects of disruptions
            or other issues impacting Ethereum or the Ethereum platform.
          </li>
        </ol>
        <h2>INDEMNIFICATION</h2>
        <p>
          {`You agree to hold harmless and indemnify Mystic Sisterhood and its
          subsidiaries, affiliates, officers, agents, employees, advertisers,
          licensors, suppliers or partners from and against any claim,
          liability, loss, damage (actual and consequential) of any kind or
          nature, suit, judgment, litigation cost, and reasonable attorneys'
          fees arising out of or in any way related to (i) your breach of these
          Terms, (ii) your misuse of the Site, or (iii) your violation of
          applicable laws, rules or regulations in connection with your access
          to or use of the Site.`}
        </p>
        <h2>CHANGES TO THE TERMS AND CONDITIONS</h2>
        <p>
          We may make changes to the Terms at our discretion. Please check these
          Terms periodically for changes. Any changes to the Terms will apply on
          the date that they are made, and your continued access to or use after
          the Terms have been updated will constitute your binding acceptance of
          the updates. If you do not agree to any revised Terms, you may not
          access or use the Site.
        </p>
        <h2>CHILDREN</h2>
        <p>
          The Mystic Sisterhood project is not targeted towards children. You
          agree that you are over the age of 18. By accessing the Site, you
          represent and warrant that you are at least 18 years of age.
        </p>
        <h2>DISCLAIMERS</h2>
        <p>
          {`YOU EXPRESSLY UNDERSTAND AND AGREE THAT YOUR ACCESS TO AND USE OF THE
          SITE IS AT YOUR SOLE RISK, AND THAT THE SITE IS PROVIDED "AS IS" AND
          "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR
          IMPLIED. TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW,
          WE MAKE NO EXPRESS WARRANTIES AND HEREBY DISCLAIM ALL IMPLIED
          WARRANTIES REGARDING THE SITE AND ANY PART OF IT (INCLUDING, WITHOUT
          LIMITATION, THE SITE, ANY SMART CONTRACT, OR ANY EXTERNAL WEBSITES),
          INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
          PARTICULAR PURPOSE, NON-INFRINGEMENT, CORRECTNESS, ACCURACY, OR
          RELIABILITY. WITHOUT LIMITING THE GENERALITY OF THE FOREGOING, WE, OUR
          SUBSIDIARIES, AFFILIATES, AND LICENSORS DO NOT REPRESENT OR WARRANT TO
          YOU THAT: (I) YOUR ACCESS TO OR USE OF THE SITE WILL MEET YOUR
          REQUIREMENTS, (II) YOUR ACCESS TO OR USE OF THE SITE WILL BE
          UNINTERRUPTED, TIMELY, SECURE OR FREE FROM ERROR, (III) USAGE DATA
          PROVIDED THROUGH THE SITE WILL BE ACCURATE, (III) THE SITE OR ANY
          CONTENT, SERVICES, OR FEATURES MADE AVAILABLE ON OR THROUGH THE SITE
          ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS, OR (IV) THAT ANY DATA
          THAT YOU DISCLOSE WHEN YOU USE THE SITE WILL BE SECURE. SOME
          JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES IN
          CONTRACTS WITH CONSUMERS, SO SOME OR ALL OF THE ABOVE EXCLUSIONS MAY
          NOT APPLY TO YOU.`}
        </p>
        <p>
          YOU ACCEPT THE INHERENT SECURITY RISKS OF PROVIDING INFORMATION AND
          DEALING ONLINE OVER THE INTERNET, AND AGREE THAT WE HAVE NO LIABILITY
          OR RESPONSIBILITY FOR ANY BREACH OF SECURITY UNLESS IT IS DUE TO OUR
          WILFUL MISCONDUCT.
        </p>
        <p>
          WE WILL NOT BE RESPONSIBLE OR LIABLE TO YOU FOR ANY LOSSES YOU INCUR
          AS THE RESULT OF YOUR USE OF THE ETHEREUM NETWORK NOR DO WE HAVE NO
          CONTROL OVER AND MAKE NO GUARANTEES REGARDING ANY SMART CONTRACTS.
        </p>
        <h2>PRIVACY POLICY</h2>
        <p>
          Mystic Sisterhood will not collect any cookies, IP addresses, or user
          data in connection with your use of the website and app, with the
          exception of cookies related to browsing behavior for the Google
          analytics SEO which helps us enhance your experience with our site and
          relay visitor traffic statistics to the Google search engine. All
          project participants understand that the Ethereum blockchain network
          is a public blockchain, and all transaction history initiated through
          the website will be made public. Mystic Sisterhood has no influence on
          secondary marketplaces, which have independent terms of service agreed
          to by you, should you choose to utilize these sites. You also
          understand that Mystic Sisterhood may work with third-party apps, such
          as Discord, which collect and store user data. Should Mystic
          Sisterhood be required to collect or store data for future activities
          such as merchandise launches or transfer of any benefits such as
          airdrops, you will be required to agree to the collection of this
          data. This provision may be subject to change, when deemed fit by the
          Mystic Sisterhood Creative Team upon due notification to the end user.
        </p>
      </div>
    </div>
  );
}
